name: github-actions-to-ci-branches
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - '**'
jobs:
  ci-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Window
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          cache: 'yarn'
      - name: Install dependencies
        run: |
          yarn
          node --version
          yarn autoclean --force
          yarn run clean
      - name: Lint
        run: yarn run lint
      - name: Test
        run: |
          yarn run unit
          yarn run e2e:impl
      - name: Post-test
        run: yarn run cucumber:report:badge
      - name: Post-test commit
        run: |
          git add test/cucumber_report.html test/cucumber_report.json README.md
          git commit -m "github-actions Updating branch from github-actions build."
          git push origin $GITHUB_REF_NAME

  ci-linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Linux
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          cache: 'yarn'
      - name: Install dependencies
        run: |
          yarn
          node --version
          yarn autoclean --force
          yarn run clean
      - name: Lint
        run: yarn run lint
      - name: Test on Linux
        run: |
          chmod +x ./scripts/*.sh
          . ./scripts/linux_headless_xvfb_init.sh
          yarn run unit
          yarn run e2e:impl
  ci-macosx:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Macosx
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          cache: 'yarn'
      - name: Install dependencies
        run: |
          yarn
          node --version
          yarn autoclean --force
          yarn run clean
      - name: Lint
        run: yarn run lint
      - name: Test
        run: |
          yarn run unit
          yarn run e2e:impl
