name: github-actions-to-ci-branches
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - '**'
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - ubuntu-18.04
          - macos-11
        node_version:
          - '14.x'
    name: OS  ${{ matrix.os }} with node ${{ matrix.node_version }}
    steps:
      - name: Checkout Windows
        if: ${{ runner.os == 'Windows' }}
        uses: actions/checkout@v2
        run: git config --global core.autocrlf input
      - name: Checkout Default
        if: ${{ runner.os != 'Windows' }}
        uses: actions/checkout@v2
      - name: Install
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - run: |
          yarn
          node --version
          yarn autoclean --force
          yarn run clean
      - name: Lint
        run: yarn run lint
      - name: Test Linux
        if: ${{ runner.os == 'Linux' }}
        run: |
          chmod +x ./scripts/*.sh
          . ./scripts/linux_headless_xvfb_init.sh
          yarn run unit
          yarn run e2e:impl
      - name: Test Default
        if: ${{ runner.os != 'Linux' }}
        run: |
          yarn run unit
          yarn run e2e:impl
      - name: Post-test
        if: ${{ runner.os == 'Windows' }}
        run: |
          yarn run cucumber:report:badge
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add test/cucumber_report.html test/cucumber_report.json README.md
          git commit -m "github-actions Updating branch from github-actions build."
          git push origin $GITHUB_REF_NAME
