name: github-actions-to-ci-branches
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - '**'
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - ubuntu-18.04
          - macos-11
        node_version:
          - '14.x'
        architecture:
          - x64
    name: OS  ${{ matrix.os }} - arch ${{ matrix.architecture }} with node ${{ matrix.node_version }}
    steps:
      - uses: actions/checkout@v2
      - name: Install
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
          cache: 'yarn'
      - run: |
          yarn
          node --version
          yarn autoclean --force
          yarn run clean
          echo ${{ runner.os }}
      - name: Lint
        run: yarn run lint
      - name: Pre-test setup
        if: ${{ runner.os == 'ubuntu-18.04' }}
        run: |
          chmod +x ./scripts/*.sh
          . ./scripts/linux_headless_xvfb_init.sh
      - name: Test
        run: |
          yarn run unit
          yarn run e2e:impl
      - name: Post-test
        if: ${{ runner.os == 'windows-2019' }}
        run: yarn run cucumber:report:badge
      - name: Post-test commit
        if: ${{ runner.os == 'windows-2019' }}
        run: |
          git add test/cucumber_report.html test/cucumber_report.json README.md
          git commit -m "github-actions Updating branch from github-actions build."
          git push origin $GITHUB_REF_NAME
