name: github-actions-to-ci-branches
on: [push, pull_request]
  push:
    branches:
      - develop
      - master
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: windows
      -run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git stash
        git merge develop
        git commit --amend -m "Merged for Windows CI test."
        git push
