name: github-actions-to-ci-branches
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - '**'
jobs:
  merge-and-run-ci-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: windows
      - run: |
          git stash
          git merge develop
          git commit --amend -m "Merged for Windows CI test."
          git push
